name:  Deploy  Platform

on:
    workflow_dispatch:

jobs:
    deploy-platform:
        runs-on:  ubuntu-latest
        steps:
            -  uses:  actions/checkout@v4

            -  name:  Azure  Login
                uses:  azure/login@v2
                with:
                    creds:  ${{  secrets.AZURE_CREDENTIALS  }}

            -  name:  Install  Bicep
                run:  az  bicep  install

            -  name:  Deploy  Management  Groups
                run:  |
                    az  deployment  tenant  create  \
                        --name  mg-deploy  \
                        --template-file  platform/management-groups/main.bicep  \
                        --parameters  rootManagementGroupId="00000000-0000-0000-0000-000000000000"
